<?php
/**
 * Agency Pass — mu-plugin loader (reference copy).
 *
 * The actual mu-plugin loader is generated by MuPluginInstaller::install()
 * during plugin activation and placed in wp-content/mu-plugins/.
 * This file serves as a reference for manual installation.
 *
 * @package Agency_Pass
 */

declare(strict_types=1);

// Auto-generated by Agency Pass. Safe to commit to version control.
$agency_pass_plugin_file = WP_PLUGIN_DIR . '/agency-pass/plugin.php';
if ( file_exists( $agency_pass_plugin_file ) ) {
	require_once $agency_pass_plugin_file;
}
