<?php

declare(strict_types=1);

namespace Agency_Pass;

/**
 * Manages the mu-plugin loader file lifecycle.
 */
class MuPluginInstaller {

	private const LOADER_FILENAME = 'agency-pass-loader.php';

	/**
	 * Installs the mu-plugin loader.
	 *
	 * @return void
	 */
	public static function install(): void {
		$target     = self::loader_path();
		$target_dir = \dirname( $target );

		if ( ! \is_dir( $target_dir ) ) {
			wp_mkdir_p( $target_dir );
		}

		\file_put_contents( $target, self::loader_content() ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents
	}

	/**
	 * Removes the mu-plugin loader.
	 *
	 * @return void
	 */
	public static function uninstall(): void {
		$target = self::loader_path();

		if ( \file_exists( $target ) ) {
			\unlink( $target ); // phpcs:ignore WordPress.WP.AlternativeFunctions.unlink_unlink
		}
	}

	/**
	 * Returns the full path to the mu-plugin loader file.
	 *
	 * @return string
	 */
	public static function loader_path(): string {
		return \WPMU_PLUGIN_DIR . '/' . self::LOADER_FILENAME;
	}

	/**
	 * Generates the mu-plugin loader PHP content.
	 *
	 * @return string
	 */
	public static function loader_content(): string {
		$plugin_file = \WP_PLUGIN_DIR . '/agency-pass/plugin.php';

		return "<?php\n"
			. "// Auto-generated by Agency Pass. Do not edit.\n"
			. "if ( file_exists( '" . $plugin_file . "' ) ) {\n"
			. "\trequire_once '" . $plugin_file . "';\n"
			. "}\n";
	}
}
